### ISSUE TITLE
JavaScript的数据类型和区别

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#103]
# 数据类型
- Undefined
- Null
- Boolean
- Number
- String
- Object
- Symbol
- BigInt

**Comment by ReinerLau1** [comment]
# 分类

**原始数据类型**
- Undefined
- Null
- String
- Number
- Boolean
- Symbol
- BigInt

**引用数据类型**
- 对象
- 数组
- 函数

**Comment by ReinerLau1** [comment]
# 区别

**原始引用类型**
- 存储在栈中
- 占据空间小
- 大小固定

**引用数据类型**
- 存储在堆中
- 占据空间大
- 大小不固定
- 在栈中存储指针

**Comment by ReinerLau1** [comment]
# ES6新增的数据类型
- Symbol：表示创建后唯一且不可变的变量，用于解决全局变量冲突的问题
- BigInt：表示任意精度格式的整数，可以安全地存储和操作超出`Number`安全范围的大整数

**Comment by ReinerLau** [comment]
# 栈和堆

**栈**
- 先进后出
- 由编译器自动分配释放

**堆**
- 优先队列，优先级可以按照大小来规定
- 由开发者分配释放，开发者不释放，程序结束时可能由垃圾回收机制回收
