### ISSUE TITLE
双向数据绑定的原理

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#313]
# 原理

- 数据劫持
- 发布订阅模式

> 数据劫持：利用Object.defineProperty对数据变化进行监听

> 发布订阅模式：一个发布者发出通知，一个或多个订阅者接收通知

![image](https://user-images.githubusercontent.com/25604088/151651845-e6a77463-d494-424a-9d40-b0d4931b41c9.png)

**Comment by ReinerLau** [comment]
![image](https://user-images.githubusercontent.com/25604088/151651845-e6a77463-d494-424a-9d40-b0d4931b41c9.png)

**Comment by ReinerLau** [comment]
# Observe

- 递归遍历所有属性值进行`Object.definedProperty`处理，监听到数据变化

**Comment by ReinerLau** [comment]
# Compile

- 将模板中变量替换成数据然后初始化视图

**Comment by ReinerLau** [comment]
# MVVM

- 数据变化更新视图
- 视图变化更新数据

**Comment by ReinerLau1** [comment]
# Observer监听器

- 递归遍历所有属性值进行`Object.definedProperty`处理实现数据变化监听
- 监听后就可以通知`Watcher`订阅者是否需要更新

**Comment by ReinerLau1** [comment]
# Complie解析器

- 将模板中的变量替换成数据后初始化视图
- 解析模板每个节点上的指令并初始化成相应订阅者

**Comment by ReinerLau1** [comment]
# Dep订阅器

- 表示发布者
- 一个属性对应一个`Dep`
- 因为订阅者有多个，所以`Dep`负责收集相关的订阅者
- 监听到数据变化时，通知相关的订阅者

**Comment by ReinerLau1** [comment]
# Watcher订阅者

- 表示订阅者
- 负责订阅`Dep`，并在订阅的时候让`Dep`进行收集
- 监听到数据变化时，接收`Dep`发布的通知执行对应的更新函数

**Comment by ReinerLau1** [comment]
# MVVM

- 整合`Observer`、`Watcher`、`Complie`三者实现数据变化更新视图，视图变化更新数据的双向数据绑定

**Comment by ReinerLau1** [comment]
# 总结

- Vue结合了**数据劫持**和**发布订阅模式**实现了双向数据绑定
- 首先设置了`Obesever`监听器递归遍历所有属性，利用`Object.defineProperty`处理实现数据监听后可以通知`Watcher`订阅者是否需要更新
- 然后`Complie`解析器将模板上的变量替换成数据后初始化视图，同时解析每个节点上的指令并初始化相应`Watcher`订阅者
- 因为`Watcher`订阅者有很多个，需要`Dep`订阅器收集相关的`Watcher`订阅者，在数据变化时订阅器通知相应订阅者执行函数更新视图
- 结合监听器、解析器、订阅者实现数据变化更新视图，视图变化更新数据的双向数据绑定
