### ISSUE TITLE
computed 和 watch 的区别和运用的场景

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#316]
# Computed

- computed 是计算属性，依赖其他属性计算值
- 并且 computed 的值有缓存，只有当计算值变化才会返回内容
- 它可以设置 getter 和 setter

**Comment by ReinerLau1** [comment]
# Watch

- watch 监听到值的变化就会执行回调，在回调中可以进行一些逻辑操作

**Comment by ReinerLau** [comment]
# 总结

- **computed**：依赖其它属性值，并且`computed`的值有缓存，只有它依赖的属性值发生改变，下一次获取`computed`的值时才会重新计算`computed`的值
- **watch**：更多的是观察的作用，无缓存性，类似于某些数据的监听回调，每当监听的数据变化时都会执行回调进行后续操作

**Comment by ReinerLau1** [comment]
# 使用场景

- computed 一般用在模板渲染中，某个值是依赖了其它的响应式对象甚至是计算属性计算而来
- watch 适用于观测某个值的变化去完成一段复杂的业务逻辑
