### ISSUE TITLE
HTML5 有哪些更新

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#7]
# 语义化标签
- header
- footer
- main
- section
- article
- aside
- nav

**Comment by ReinerLau1** [comment]
# 媒体标签
- audio
- video
- source

**Comment by ReinerLau1** [comment]
# 表单

**表单类型**
- email
- url
- number
- search
- range
- color
- time
- date
- datetime
- datetime-local
- week
- month

**表单属性**
- placeholder
- autofocus
- autocomplete
- required
- pattern
- multiple
- form

**表单事件**
- oninput
- oninvalid

**Comment by ReinerLau** [comment]
# 进度条、度量器
- progresss
- meter

**Comment by ReinerLau1** [comment]
# DOM查询
- document.querySelector
- document.querySelectorAll

**Comment by ReinerLau1** [comment]
# 存储
- localStorage
- sessionStorage

**Comment by ReinerLau1** [comment]
# 其他
- progress
- meter
- draggable
- canvas
- svg
- geolocation
- websocket

**Comment by ReinerLau1** [comment]
# 移除元素
- 纯表现的元素：basefont，big，center，font, s，strike，tt，u
- 对可用性产生负面影响的元素：frame，frameset，noframes

**Comment by ReinerLau1** [comment]
# history api
- go
- forward
- back
- pushstate
