### ISSUE TITLE
什么是同源策略

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#91]
# 概念

同源策略限制了从同一个源加载的文档或脚本如何与另一个源的资源进行交互。这是浏览器的一个用于隔离潜在恶意文件的重要的安全机制。同源指的是：协议、端口号、域名必须一致

**Comment by ReinerLau** [comment]
# 同源

- 两个URL协议相同
- 两个URL域名相同
- 两个URL端口相同

**Comment by ReinerLau1** [comment]
# 限制

- 当前域下的 js 脚本不能够访问其他域下的 cookie、localStorage 和 indexDB。
- 当前域下的 js 脚本不能够操作访问操作其他域下的 DOM。
- 当前域下 ajax 无法发送跨域请求。

**Comment by ReinerLau1** [comment]
# 目的

同源政策的目的主要是为了保证用户的信息安全，它只是对 js 脚本的一种限制，并不是对浏览器的限制，对于一般的 img、或者script 脚本请求都不会有跨域的限制，这是因为这些操作都不会通过响应结果来进行可能出现安全问题的操作

**Comment by ReinerLau** [comment]
# 跨域资源共享和跨文档消息机制

- 为了让站点可以请求不同源的资源，引入了跨域资源共享（CORS）
- 为了让不同源的DOM之间进行通信，引入了跨文档消息机制，可以通过`window.postMessage`实现
