### ISSUE TITLE
对CSRF攻击的理解

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#93]
# 概念

- 指的是跨站请求伪造攻击，攻击者诱导用户进入一个第三方网站，然后该网站向被攻击网站发送跨站请求。如果用户在被攻击网站中保存了登录状态，那么攻击者就可以利用这个登录状态，绕过后台的用户验证，冒充用户向服务器执行一些操作
- 本质是利用 cookie 会在同源请求中携带发送给服务器的特点，以此来实现用户的冒充

**Comment by ReinerLau1** [comment]
# 攻击类型

- **GET 类型的 CSRF 攻击**：比如在网站中的一个 img 标签里构建一个请求，当用户打开这个网站的时候就会自动发起提交。
- **POST 类型的 CSRF 攻击**：比如构建一个表单，然后隐藏它，当用户进入页面时，自动提交这个表单。
- **链接类型的 CSRF 攻击**：比如在 a 标签的 href 属性里构建一个请求，然后诱导用户去点击。

**Comment by ReinerLau1** [comment]
# 防御

- **进行同源检测**：服务器根据 http 请求头中 origin 或者 referer 信息来判断请求是否为允许访问的站点，从而对请求进行过滤。当 origin 或者 referer 信息都不存在的时候，直接阻止请求。这种方式的缺点是有些情况下 referer 可以被伪造，同时还会把搜索引擎的链接也给屏蔽了。所以一般网站会允许搜索引擎的页面请求，但是相应的页面请求这种请求方式也可能被攻击者给利用。（Referer 字段会告诉服务器该网页是从哪个页面链接过来的）
- **使用 CSRF Token 进行验证**：服务器向用户返回一个随机数 Token ，当网站再次发起请求时，在请求参数中加入服务器端返回的 token ，然后服务器对这个 token 进行验证。这种方法解决了使用 cookie 单一验证方式时，可能会被冒用的问题，但是这种方法存在一个缺点就是，我们需要给网站中的所有请求都添加上这个 token，操作比较繁琐。还有一个问题是一般不会只有一台网站服务器，如果请求经过负载平衡转移到了其他的服务器，但是这个服务器的 session 中没有保留这个 token 的话，就没有办法验证了。这种情况可以通过改变 token 的构建方式来解决
- **对 Cookie 进行双重验证**：服务器在用户访问网站页面时，向请求域名注入一个Cookie，内容为随机字符串，然后当用户再次向服务器发送请求的时候，从 cookie 中取出这个字符串，添加到 URL 参数中，然后服务器通过对 cookie 中的数据和参数中的数据进行比较，来进行验证。使用这种方式是利用了攻击者只能利用 cookie，但是不能访问获取 cookie 的特点。并且这种方法比 CSRF Token 的方法更加方便，并且不涉及到分布式访问的问题。这种方法的缺点是如果网站存在 XSS 漏洞的，那么这种方式会失效。同时这种方式不能做到子域名的隔离
- **在设置 cookie 属性的时候设置 Samesite**：限制 cookie 不能作为被第三方使用，从而可以避免被攻击者利用。Samesite 一共有两种模式，一种是严格模式，在严格模式下 cookie 在任何情况下都不可能作为第三方 Cookie 使用，在宽松模式下，cookie 可以被请求是 GET 请求，且会发生页面跳转的请求所使用

**Comment by ReinerLau** [comment]
# 利用Cookie的SameSite属性

- 被调用接口的服务器可以设置`Set-Cookie`字段的`SameSite`属性有`Strict`、`Lax`和`None`三种
- Strict：浏览器不允许用户向第三方请求接口时携带Cookie
- Lax：浏览器只允许从第三方站点的链接打开和从第三方站点提交GET方式的表单这两种方式都会携带Cookie，POST请求、img、iframe都不会携带Cookie
- None：任何情况都携带Cookie

**Comment by ReinerLau** [comment]
# 验证请求的来源站点

- 服务器根据请求体中`Referer`和`Origin`属性判断请求是否来源于第三方站点，然后禁止第三方站点的请求
- `Referer`属性包含路径信息
- `Origin`属性只包含域名信息

**Comment by ReinerLau** [comment]
# CSRF Token

- 浏览器向服务器发起请求，服务器生成`Token`字符串，存入到当前页面
- 浏览器再次发起请求带上之前生成的`Token`，服务器验证`Token`是否合法
- 从第三方站点发起请求无法获取当前页面的`Token`，服务器会拒绝请求
