### ISSUE TITLE
对HTTPS的理解

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#95]
# HTTP的问题

- HTTP是明文传输
- 传输过程中会经过用户电脑、WIFI路由器、运营商、目标服务器的几个中间环节，每个环节都有可能被窃取或篡改

**Comment by ReinerLau1** [comment]
# HTTPS

- 在HTTP基础上添加安全层
- 安全层主要负责对请求数据进行加密操作，对响应数据进行解密操作

**Comment by ReinerLau1** [comment]
# 数字证书加密

**Comment by ReinerLau** [comment]
# 数字证书加密
